From python:3.12

WORKDIR /app

COPY deployment/ deployment/
COPY src/ src/
COPY models/ models/

RUN pip install -r deployment/requirements.txt

CMD ["uvicorn","deployment.app:app","--host","0.0.0.0","--port","6000"]