FROM python:3.12-slim

WORKDIR /app

COPY deployment/ deployment/
COPY src/ src/

RUN pip install -r deployment/requirements.txt

CMD ["uvicorn","deployment.app:app","--host","0.0.0.0","--port","10000"]